# Generated by Django 3.2 on 2023-02-14 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusuario',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Repita o Email'),
        ),
    ]
